eeps/eep-0049.md

Add content on comparisons with Elixir's `with`, and expand on not
supporting all ok- and error-based tuples following community feedback

Update EEP 49 (eep-0049.md)

---

eeps/eep-0051.md

See https://github.com/erlang/otp/pull/2324

Add EEP-51: Underscore digit separator in numeric literals

---

eeps/eep-0054.md

The OTP Technical Board approved the EEP, but requested a few
changes:
* The optional `module` and `function` keys in the map will point
the module and function for a `format_error` function.
* The arguments for `format_error` has been simplified to just
two arguments: The exception reason and the first entry in
stacktrace.
Taken together, those to changes makes it easy to have one module
with a `format_error/2` that can explain errors for multiple
modules.

Update EEP-54 according to the decision of OTB

---

eeps/eep-0056.md

This update implements suggestions from the eeps mailing list and adds a few paragraphs for clarification:
* Fixed grammar: "childs" --> "children"
* The supervisor flag `shutdown` was renamed to `auto_shutdown`, and the value `normal` to `never`, which should be clearer
* Clarified the purpose of the `never` option for the `auto_shutdown` supervisor flag
* Added a paragraph about significant children in `simple_one_for_one` supervisors

Update EEP 56

---

eeps/eep-0054.md

The `general` return key was added in order to allow information
to be given about the default I/O device in [io:format("hello")][io_format_1].
It also allows third-party error_report implementations (such as Elixir)
much more freedom in what they can return.
The `reason` return key was added in order for third-party error_report
implementations (such as Elixir) to influence what is printed to describe
the actual error.
[io_format_1]: http://erlang.org/doc/man/io.html#format-1

eep54: Add general and reason to return map

---

eeps/eep-0049.md

Introduce `maybe` as keyword to start the construct and `<~' as matching operator.

Update eep-0049 with decisions from OTP Technical Board

---

eeps/eep-0057.md

Extend the syntax to allow multiple matches of a case statement to share the same body.

Add EEP-0057: Implement alternative patterns for expression matching

---

eeps/eep-0064.md

This EEP discusses the design of the triple-quoted binary strings.
In the case that document attributes [EEP 59](https://www.erlang.org/eeps/eep-0059) and interpolation strings ([EEP 62](https://github.com/erlang/eep/pull/45)) are added before this EEP, interpolation attributes are to be disallowed in documentation attributes (this is mentioned in the EEP).
The semantics should feel familiar for Elixir developers, and should be pretty close to Elixir triple-quote semantics.
Feedback is welcome.

EEP 64: Triple-Quoted Strings

---

eeps/eep-0064.md

3-or-more-quoted strings may have potential for
bigger backwards compatibility.

Updates of EEP 64

---

eeps/eep-0064.md

The OTB decided that empty lines should be allowed to be completely empty in addition to containing the defined indentation.

Update after OTP Technical Board 2023-08-31

---

eeps/eep-0067.md

EEP for introducing the concept of *internal exports*. For details, look in the EEP itself and in the PR of reference implementation.
P.S. Do I need to send it on the mailing list?

EEP: internal export

---

eeps/eep-0068.md

This EEP proposes adding a `json` module to the standard library
[Rendered](https://github.com/michalmuskala/eep/blob/json-eep/eeps/eep-0068.md)

EEP68 - JSON

---

eeps/eep-XXX.md

This commit adds the eep draft for nominal types. I plan to make a post on Erlang forum, introducing nominal types. The post will refer to this pull request.

Added eep draft for nominal types

---

eeps/eep-0071.md

Type variables are an often-used yet very misunderstood part of the type
language. As `dialyzer` has been lax in enforcing their defined semantics owing
to a few bugs, many users have been led to believe that they are simple generics
as in most other languages. As a significant amount of code has been written
with this in mind, OTP cannot fix the bugs that made `dialyzer` lax by accident
without breaking the analysis of a lot of code.
While that would be fine if `dialyzer` were the only tool out there, all the
other code analyzers we know of interpret type variables as generics which would
fragment the ecosystem should we elect to fix the bugs. One application might
have been written with `eqWAlizer` in mind and another with `dialyzer`,
preventing either tool from being applied to the …

EEP 71: clarification of type specs & generics

---

eeps/eep-0072.md

Hello,
This is in reference to [PR-7873](https://github.com/erlang/otp/pull/7873) and is made on @RaimoNiskanen's [recommendation](https://github.com/erlang/otp/pull/7873#issuecomment-2346314677).
@RaimoNiskanen, I did not include you as an author on the EEP, but since you implemented the new record syntax, you obviously deserve to be on it.  I just didn't want to include you without your blessing first.

Update record names as reserved words/variables and new record definition syntax

---

eeps/eep-0070.md

This is an EEP accompanying erlang/otp#8625 that proposes the addition of a new, *non-skipping* variant of all existing generators (list, bit string and map).  Currently existing generators are *skipping*: they ignore terms in the right-hand side expression that do not match the left-hand side pattern.  Non-skipping generators on the other hand shall fail with exception `badmatch`.

Add proposal for non-skipping generators

---

eeps/eep-0073.md

This EEP proposes the addition of zip generators with a syntax of `&&` for 
comprehensions in Erlang. The idea and syntax of zip generators (comprehension
multigenerators) was first brought up by EEP-19. Even if the syntax and
usages of zip generators proposed by this EEP is mostly the same with EEP-19,
the comprehension language of Erlang has undergone many changes since EEP-19
was accepted. With an implementation that is compatible with all existing
comprehensions, this EEP defines the behavior of zip generators with more
clarification on the compiler's part.

Zip generator for comprehensions

---

eeps/eep-0033.md

The markdown lint check does not accept multiple blank lines.

Update instructions on leaving blank lines

---

eeps/eep-0077.md

This EEP adds assignments to comprehension qualifier lists.
Reference implementation PR: https://github.com/erlang/otp/pull/9153

Draft: comprehension assignment

---

eeps/eep-0075.md

This EEP adds floating point literals using other bases than ten, such as 16 or 2, for exact text representation, as also found in Ada and C99/C++17.
Implementation PR: https://github.com/erlang/otp/pull/9106

Draft: based floating point literals

---

eeps/eep-0078.md

**TL;DR**: This EEP proposes enhancing the comprehension syntax to allow emitting multiple
elements in a single iteration of the comprehension loop - effectively enhancing
comprehensions to implement `flatmap` with a fixed number of elements, for example:
```
[X + 1, X + 2, ... || X <- Xs]
```

EEP 78: Multi-valued comprehensions
